json.id user.id
json.email user.email
json.account_status user.account_status
json.trial_end_date user.trial_end_date
json.recently_subscribed user.recently_subscribed?
json.admin user.admin
json.on_listify_team user.on_listify_team?
json.enabled_modules user.enabled_module_names
json.account_locked user.account_locked
