import React from 'react';
import PropTypes from 'prop-types';
import resultsEmptyState from '../../../assets/images/resultsEmptyState.png'; // with import

const NoResultsContent = ({ visible }) => {
  if (visible) {
    return (
      <div className="w-full h-full lg:h-screen">
        <div className="flex flex-col items-center py-4 pt-24 w-full h-full">
          <img className="mx-auto" src={resultsEmptyState} alt="see results here" width="200" height="200"></img>
          <h1 className="mt-10 text-xl font-medium tracking-wider text-gray-700">Nothing to see yet</h1>
          <p className="my-2 text-sm tracking-wider text-center text-gray-700">Results generated by our AI will appear here.</p>
        </div>
      </div>
    )
  } else {
    return null;
  }
}

NoResultsContent.propTypes = {
  visible: PropTypes.bool
};


export default NoResultsContent;
